# Generated by Django 4.1.2 on 2022-10-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0002_link_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
