# Generated by Django 4.1.2 on 2022-10-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener_api', '0003_link_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='counter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
