version: '3.8'

services:
  admin_api:
    container_name: django_api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - 8000:8000

  admin_db:
    container_name: django_admin_db
    image: sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - local_sqllite_data:./root/db
    networks:
      - ecosystem_network